cs:
  azusa:
    networks:
      somenet
        allowedIPs:
          - "192.0.2.0/24"
        allowedSRVs:
          - priorityMax: 65535
            priorityMin: 0
            service: "_service"
            serviceAny: false
            weightMax: 65535
            weightMin: 0
        canForward: false
        canSee:
          only:
            - "othernode"
        host: "thisnode.example.net"
        name: "thisnode"
  comment: "comment about this CS"
  endpoint: "cs.example.net:39252"
  networks:
    - somenet
  tls:
    certPath: "/etc/qrystal-node/cert.pem"
  tokenPath: "/etc/qrystal-node/token"
endpointOverride:
hokuto:
  addr: "127.0.0.39"
  parent: ".qrystal.internal"
trace:
  outputPath: /tmp/qrystal-trace
  waitUntilCNs: [ "somenet" ]
